### ISSUE TITLE
stale link to libxs

### ISSUE THREAD

**Issue by djw1149** [farsightsec/nmsg#56]
README.md in nmsg points to http://www.crossroads.io/ which appears to be down.  After a lot of searching and bad links, I found a libxs v1.2.0 source blob at 
http://ftp.de.debian.org/debian/pool/main/libx/libxs/libxs_1.2.0.orig.tar.gz

Sha256 Checksum: 525dc999cc6524779bc4eef510e423077b7f7ea491cb3ad6d8056ecaf99ff515

Need to update README.md to use it.

Maybe also update README.me to explain why it might be ok to configure --without-ns

**Comment by cmikk** [comment]
Fixed with switch to zmq in 1.0
