### ISSUE TITLE
get rid of the protobuf version warnings

### ISSUE THREAD

**Issue by reedjc** [farsightsec/nmsg#69]
Explicitly specify the protocol version?
 
 GEN      nmsg/nmsg.pb-c.c
[libprotobuf WARNING google/protobuf/compiler/parser.cc:547] No syntax
specified for the proto file: nmsg/nmsg.proto. Please use 'syntax =
"proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted
to proto2 syntax.)
...
  GEN      nmsg/base/dnstap.pb-c.c
[libprotobuf WARNING google/protobuf/compiler/parser.cc:547] No syntax
specified for the proto file: nmsg/base/dnstap.proto. Please use 'syntax =
"proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted
to proto2 syntax.)

**Comment by morrowc** [comment]
This is done, acutally in:
  https://github.com/farsightsec/nmsg/pull/78

so, maybe read and accept that PR? :)

**Comment by morrowc** [comment]
this is fixed now, I believe.
