### ISSUE TITLE
release tarballs should install manpage even without docbook

### ISSUE THREAD

**Issue by edmonds** [farsightsec/nmsg#9]
release tarballs currently do not install the nmsgtool(1) manpage if the docbook toolchain (and related dependencies) aren't installed even though they ship with a compiled `doc/docbook/nmsgtool.1` file.

possibly commit `doc/docbook/nmsgtool.1` (even though it is a generated file) to the repository, so that `dist_man_MANS = doc/docbook/nmsgtool.1` can be made into an unconditional rule (and not dependent on `BUILD_MAN`).

or possibly come up with a workaround in `configure.ac` / `Makefile.am` that installs the `nmsgtool.1` file if it's present in the source tree.

**Comment by reedjc** [comment]
Sorry I didn't see this ticket. This was handled in internal issue 12. commit  f9f382c91 was merged to upstream next (which will get here soon).
