### ISSUE TITLE
Missing Mailing list .. it seems to have sneaked off into the ether! :)

### ISSUE THREAD

**Issue by morrowc** [farsightsec/nmsg#94]
README.md says:

"Questions about `libnmsg`, `nmsgtool`, `pynmsg`, the development of `libnmsg`
client programs or language bindings, or the `NMSG` binary protocol should be
directed to the `nmsg-dev` mailing list:

https://lists.farsightsecurity.com/mailman/listinfo/nmsg-dev"

but:
$ host !$
host lists.farsightsecurity.com
Host lists.farsightsecurity.com not found: 3(NXDOMAIN)

where did it go? (asking because I have a question about python nmsg and debian buster support of same)

**Comment by cmikk** [comment]
'lists' has been retired, and we will clean up the stale link here (and in the wdns repo) soon.

I suggest opening a github issue here (or on pynmsg, more likely) regarding buster support, and we'll take it from there.

**Comment by morrowc** [comment]
thanks!
