### ISSUE TITLE
Buster - it's the new Wheezy / Stretch (or something like that)

### ISSUE THREAD

**Issue by morrowc** [farsightsec/nmsg#95]
We're well into the lifecycle of Debian Buster (10.6 even!) could the nmsg stack get debian packages built and published for buster please? 

thanks!

**Comment by alesage** [comment]
We're eager to get these started, yes, I'll take assignment of this.

**Comment by reedjc** [comment]
I created a new repo with the following sources.list:
deb http://dl.farsightsecurity.com/debian buster-farsightsec main
(amd64 only)
It has: nmsgtool nmsg-msg-module-sie libnmsg-dev nmsg-msg-module-sie-dev libwdns-dev python-nmsg
Will this work for your current needs?
Note that later we will add more open source packages including python3 modules.

**Comment by morrowc** [comment]
swapping stretch/buster, re-running apt-update/ugprade...

Picking just the nmsgtool package for example:
Package: nmsgtool
Status: install ok installed
Priority: optional
Section: net
Installed-Size: 272
Maintainer: Farsight Security, Inc. <software@farsightsecurity.com>
Architecture: amd64
Source: nmsg
Version: 0.15.1-1+fsi9
Depends: libc6 (>= 2.4), libnmsg6 (>= 0.14.0), libpcap0.8 (>= 1.0.0), libxs2, zlib1g (>= 1:1.1.4)
Description: network message encapsulation tool

that seems ok... let's see how it works :)
he following packages will be upgraded:
  libnmsg-dev libnmsg6 libwdns1 nmsg-flt1-module-sample nmsg-msg-module-sie nmsg-msg-module-sie-dev nmsg-msg9-module-base
  nmsg-msg9-module-sie nmsgtool python-nmsg
10 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 683 kB of archives.
After this operation, 179 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://dl.farsightsecurity.com/debian buster-farsightsec/main amd64 libwdns1 amd64 0.10.0-1+fsi10 [31.2 kB]
Get:2 http://dl.farsightsecurity.com/debian buster-farsightsec/main amd64 nmsg-msg9-module-base amd64 0.15.1-1+fsi10 [124 kB]
Get:3 http://dl.farsightsecurity.com/debian buster-farsightsec/main amd64 nmsg-flt1-module-sample amd64 0.15.1-1+fsi10 [19.8 kB]
Get:4 http://dl.farsightsecurity.com/debian buster-farsightsec/main amd64 libnmsg-dev amd64 0.15.1-1+fsi10 [44.6 kB]
Get:5 http://dl.farsightsecurity.com/debian buster-farsightsec/main amd64 libnmsg6 amd64 0.15.1-1+fsi10 [264 kB]
Get:6 http://dl.farsightsecurity.com/debian buster-farsightsec/main amd64 nmsg-msg9-module-sie amd64 1.2.1-1+fsi10 [10.6 kB]
Get:7 http://dl.farsightsecurity.com/debian buster-farsightsec/main amd64 nmsg-msg-module-sie all 1.2.1-1+fsi10 [2,336 B]
Get:8 http://dl.farsightsecurity.com/debian buster-farsightsec/main amd64 nmsg-msg-module-sie-dev amd64 1.2.1-1+fsi10 [4,960 B]
Get:9 http://dl.farsightsecurity.com/debian buster-farsightsec/main amd64 nmsgtool amd64 0.15.1-1+fsi10 [96.4 kB]
Get:10 http://dl.farsightsecurity.com/debian buster-farsightsec/main amd64 python-nmsg amd64 0.4.0-1+fsi10 [86.1 kB]
Fetched 683 kB in 0s (6,688 kB/s)       


$ python
Python 2.7.16 (default, Oct 10 2019, 22:02:15) 
[GCC 8.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import nmsg
>>> 

that seems very positive...
and with inbound mail processing, I see positive activity :) 

thanks!
